### PR TITLE
Refactor Prv to Pri

### PR DESCRIPTION
**Pull request by ColonelPanicks**
Based on #43 so merge that first.

This addresses #31.

### CODE REVIEW

**Comment by WilliamMcCumstie** [comment]
Closing this issue to the problems associated with #43. I have however applied the `prv` to `pri` change on one of my branches

**Comment by mjtko** [comment]
I'm confused about the state of this PR now -- which branch have you applied `prv` -> `pri` changes on @WilliamMcCumstie?

Can you reference branches/commit refs in comments when referring to them pls?

**Comment by WilliamMcCumstie** [comment]
Sorry for the delay, I need to remove the old commit and rebase the branches. This original PR was causing was causing conflicts when I was rebasing @ColonelPanicks on mine. In the end it was easier to drop the original commit and redo the replacement.

**Comment by mjtko** [comment]
Ok, great, thanks for the explanation! 😍

**Pull request closed without merging**
